spring:
  application:
    name: bkk-route-crawler
  main:
    banner-mode: "off"
  jpa:
    ddl-auto: update
    hibernate:
      show_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource:
    url: "jdbc:mysql://localhost:3306/routes?rewriteBatchedStatements=true&useUnicode=yes&characterEncoding=UTF-8"
    driverClassName: com.mysql.jdbc.Driver
    username: "spring"
    password: "spring"

management:
  server:
    port: 9001
  endpoint:
    health:
      show-details: "ALWAYS"
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8002
  servlet:
    application-display-name: "BKK"
    context-path: /bkk

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL

scheulder:
  bkkkScheulder:  "0 0/5 0 ? * * *"

bkk:
  apiUrl: "https://futar.bkk.hu/api/query/v1/ws/otp/api/where/"
  apiKey: "bkk-web"
  appVersion: "apiary-1.0"
  version: 3

weather:
  url: "http://localhost:8001/bkk"
  fileSystemPath: "weatherproperties.json"
  bottomLeftLat: 47.1523107
  bottomLeftLong: 18.8460594
  topRightLat: 47.6837053
  topRightLong: 19.391385500000002
  chunkWideSize: 10
  chunkHighSize: 6
